server:
  port: 8080

wechat:
  appId: ww164a24f6c9e8898b
  appsecret: Gm_pKaYPxNHfNXj3TiwzCPkF55Y4yLlo8kykSh0OK7E
  accessTokenUrl: https://qyapi.weixin.qq.com/cgi-bin/gettoken
  spNoListUrl: https://qyapi.weixin.qq.com/cgi-bin/oa/getapprovalinfo
  dataUrl: https://qyapi.weixin.qq.com/cgi-bin/oa/getapprovaldetail

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/mysqlDb?characterEncoding=utf-8
      username: root
      password: 123456